config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :users

end

app/models/tweet.rb
# == Schema Information
#
# Table name: tweets
#
#  id           :integer          not null, primary key
#  tweet_id     :string
#  text         :string
#  user_id      :integer
#  lat          :float
#  long         :float
#  for_sq       :boolean
#  text_keyword :string
#  search_word  :string
#  tweeted_at   :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
# Indexes
#
#  index_tweets_on_search_word  (search_word)
#  index_tweets_on_tweeted_at   (tweeted_at)
#  index_tweets_on_user_id      (user_id)
#

class Tweet < ActiveRecord::Base
  belongs_to :user

  scope :geo, -> { where.not(lat: nil) }
  scope :forsq, -> { where(search_word: '4sq') }
  scope :going, -> { where(search_word: '行く') }
  scope :oldest, -> { order(:tweeted_at).first }

  def self.new_4sq(user, tw)
    Tweet.new(
        user_id: user.id,
        tweet_id: tw.id,
        text: tw.text,
        search_word: '4sq',
        tweeted_at: tw.created_at
    )
  end

  def self.new_geo(user, tw)
    Tweet.new(
        tweet_id: tw.id,
        user_id: user.id,
        text: tw.text,
        tweeted_at: tw.created_at,
        lat: tw.geo.lat,
        long: tw.geo.long
    )
  end

  def self.new_tw(user, tw, word)
    Tweet.new(
        user_id: user.id,
        tweet_id: tw.id,
        text: tw.text,
        search_word: word,
        tweeted_at: tw.created_at
    )
  end

  def self.day_count
    tweets = Tweet.order(:tweeted_at)
    start_time = tweets.first.tweeted_at
    last_time = tweets.last.tweeted_at
    (start_time.to_date..last_time.to_date).map do |date|
      count = tweets.where(tweeted_at: date.beginning_of_day..date.end_of_day).count
      [date, count]
    end.to_h
  end

  def self.hour_count(where={})
    tweets = Tweet.where(where).order(:tweeted_at)
    start_time = tweets.first.tweeted_at
    last_time = tweets.last.tweeted_at
    (start_time.to_date..last_time.to_date).map do |date|
      [date, (0...24).map do |h|
        tweets.where(tweeted_at: (date + h.hour)...(date + h.hour + 1.hour)).count
      end]
    end.to_h
  end

  def self.hour_count_geo
    hour_count('lat IS NOT NULL')
  end

  def self.hour_count_word(word)
    hour_count(search_word: word)
  end

  def self.data_terms_all
    tweets = Tweet.order(:tweeted_at)
    {
        'geo' => [tweets.geo.first, tweets.geo.last],
        '4sq' => [tweets.forsq.first, tweets.geo.last],
        'going' => [tweets.going.first, tweets.going.last]
    }
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweet_id, :text, :user_id)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tweet_id %><br>
    <%= f.text_field :tweet_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Tweet</th>
      <th>Text</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.tweet_id %></td>
        <td><%= tweet.text %></td>
        <td><%= tweet.user_id %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tweet:</strong>
  <%= @tweet.tweet_id %>
</p>

<p>
  <strong>Text:</strong>
  <%= @tweet.text %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user_id %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>